Toolbox autoupdate
Caascad/toolbox pull request #230
Opened 2021-08-05 15:33 UTC by lde

Missing Update on Github action pending.

2021-08-06 14:31 UTC, q-b requested changes

2021-08-06 14:31 UTC, q-b commented on autoupdate/update.py
> +    query += '}'
On boucle déjà avec la valeur `pkg`, pourquoi aller chercher les infos dans `pkgs[key]` ?
```
pkgs[pkg]['alias'] --> pkg.get('alias', '')
```

Ce serait aussi peut-être plus lisible avec des f-strings ?

2021-08-06 14:31 UTC, q-b commented on autoupdate/update.py
> +            exit(1)
`import sys` et `sys.exit`

2021-08-06 14:31 UTC, q-b commented on autoupdate/update.py
> +            pkgs[pkg]['repo'] = nixpkgs[pkg]['repo']
On a déjà l'assertion que pkg n'existe pas, ça peut être simplifié en créant : 
```
pkgs[pkg] = {
    'owner': nixpkgs[pkg].get('owner'),
    'repo': nixpkgs[pkg].get('repo')
}
```
par exemple

2021-08-06 14:31 UTC, q-b commented on autoupdate/update.py
> +def update_package(token, pkgs, pkg, version=None):
Si `pkg` est passé sous forme de dict je pense que `pkgs` est inutile dans cette fonction

2021-08-06 14:31 UTC, q-b commented on autoupdate/update.py
> +    if version is None:
Ici on est test sur un `None`, quel est le comportement sur un chaine vide par exemple ? Est-ce qu'on considère ça aussi comme *latest* ?

2021-08-06 14:31 UTC, q-b commented on autoupdate/update.py
> +    token = os.environ['GITHUB_TOKEN']
Un petit check/message quand le token n'est pas présent peut-être ?

2021-08-06 14:31 UTC, q-b commented on autoupdate/update.py
> +                    sha = re.compile(REGEX_SHA).search(fbuild.stderr.decode())
Ici on est à l'intérieur la boucle. Il faudrait bouger le `compile` avant celle-ci pour le réutiliser à chaque search et bénéficier du gain de perfs.

2021-08-06 15:13 UTC, lde commented on autoupdate/update.py
> +    if version is None:
non sur une chaine vide le champ est présent donc on tente de mettre à jour sur une release. c'est ce qui est voulu

2021-08-09 13:26 UTC, romainDavaze commented on autoupdate/update.py
> +REGEX_SHA = '(?<=got: {4}sha256:).*'
Peut-être combiner les deux dans une seule variable vu que `REGEX_SHA` n'est pas utilisé ailleurs.

2021-08-09 13:26 UTC, romainDavaze commented on autoupdate/update.py
> +    token = os.environ['GITHUB_TOKEN']
```suggestion
    token = os.getenv('GITHUB_TOKEN')
    if token is None:
        print('\033[91mGITHUB_TOKEN env variable is mandatory\033[0m\n')
        sys.exit(1)
```

2021-08-09 13:26 UTC, romainDavaze commented on default.nix
> +        kubernetes-alpha= {};
```suggestion
        kubernetes-alpha = {};
```

2021-08-09 13:26 UTC, romainDavaze commented on autoupdate/update.py
> +        print(nodes)
```suggestion
```

2021-08-09 13:40 UTC, q-b approved these changes

2021-08-09 13:45 UTC, romainDavaze approved these changes

2021-08-09 15:56 UTC, merged